apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "dev.gamelink.asia"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-service
                port:
                  number: 80